Added README and LEIAME for PT-BR Version
code-club-brasil/bingo pull request #1
Opened 2021-01-16 13:21 UTC by gfechio

2021-01-16 16:33 UTC, thiagonache requested changes
Vamos seguir o padrao internacional para nomenclatura.
Acho legal termos em portugues, mas vamos chamar de README_ptbr.md

2021-01-16 16:33 UTC, thiagonache commented on LEIAME.md
> +Este repo tem o objetivo de criar um jogo de Bingo escrito em [GoLang] (https://golang.org/), usando técnicas de aprendizagem entre pares para contribuir e ensinar cada um dos membros dispostos a apr
```suggestion
Este repo tem o objetivo de criar um jogo de Bingo escrito em [GoLang] (https://golang.org/), usando técnicas de aprendizagem entre pares para contribuir e ensinar cada um dos membros dispostos a aprender mais sobre a linguagem e avançar os estudos sobre Desenvolvimento de Software.
```

2021-01-16 16:33 UTC, thiagonache commented on LEIAME.md
> +- Use mensagens de confirmação apropriadas
algumas palavras fica estranha a traducao. eu usaria `mensagens de commit apropriadas`

2021-01-16 16:33 UTC, thiagonache commented on LEIAME.md
> +- Use PRs para empurrar novos commits
```suggestion
- Use PRs para enviar novos commits
```

2021-01-16 16:33 UTC, thiagonache commented on README.md
> +This repo has the objective to create a Bingo game written in [GoLang](https://golang.org/), using peer to peer learning techniques to contribute and teach each of the willing members to lern more ab
```suggestion
This repo host a Bingo game is written in [GoLang](https://golang.org/), using peer to peer learning techniques to contribute and teach each of the willing members to learn more about the language and advance in one's studies about Software Developing.
```

2021-01-18 10:21 UTC, thiagonache commented
@gfechio pode trabalhar nessas mudancas por favor?

2021-01-18 13:33 UTC, gfechio commented
Feito!

2021-01-18 18:04 UTC, thiagonache approved these changes
yep!

2021-01-18 18:04 UTC, merged